### ISSUE TITLE
Question/opinion: New green

### ISSUE THREAD

**Issue by dieggsy** [emacsfodder/emacs-theme-darktooth#35]
This is entirely a matter of opinion, but I was wondering the reason/line of thought behind the updated green in commit `3b5441b`. It seems a little more jarring/out of place in comparison to some of the other colors. In any case, I can do as I wish with my fork so this isn't a big deal.

**Comment by jasonm23** [comment]
Sorry for the late response and that you didn't like the change. As far as the reasoning/line of thought, the change was arbitrary.  I try to exercise a relatively high degree of self discipline in maintaining the palette as is.  I dont want to mess with a working formula, but I was using this theme every day since it was created and had growing dislike for original green. Finally I had to change it.

I wouldn't be averse to reverting the change.  I use my Creamsody theme now so there's no reason for me to impose an unwanted change. If anyone else doesn't like it, I'd be happy to change it back. If I see some +1's on your issue I could take action, ok?

Let me know what you think.

**Comment by dieggsy** [comment]
Thanks for your response! That sounds like a perfectly reasonable course of action. In any case, I appreciate your consideration for my concerns, and even if this doesn't bother others, I can resolve this on my end.

**Comment by jasonm23** [comment]
I was reminded today that there is a Darktooth ports project, so that's a pretty concrete reason to maintain the canonical palette

**Comment by jasonm23** [comment]
Rolling back green change in @3b5441b

**Comment by jasonm23** [comment]
9b349813bee4e0b0f1c89e6e9796f43de3930fc5
