### ISSUE TITLE
Package autothemer-0.2 is unavailable

### ISSUE THREAD

**Issue by peebz** [emacsfodder/emacs-theme-darktooth#37]
Using Emacs 24.5.1 on Ubuntu 16.4 and have just been invited to update darktooth-theme-0.2.2.  When I have tried to do so however, I get the error 'package autothemer-0.2 is unavailable'.  I can't see that any changes have been made in darktooth-theme to create this.  I'd appreciate any suggestions.

**Comment by jasonm23** [comment]
That's unfortunate, please use MELPA Stable for Darktooth.

Or you can install Autothemer manually

https://github.com/sebastiansturm/autothemer

(BTW this version should not be popping up on MELPA, I'll address that shortly.)

**Comment by jasonm23** [comment]
If this is happening on MELPA Stable I know why.

Can fix shortly.

**Comment by peebz** [comment]
Many thanks jasonm23.  I've just checked and I am using MELPA stable.

**Comment by jasonm23** [comment]
It's because I tagged my development spike.

I've added a new tag 0.1.65a MELPA Stable will pick it up on the next build cycle.

Feel free to close / comment when it's deployed.  If I spot it on MELPA feed I'll ping here too.

**Comment by peebz** [comment]
Many thanks for sorting this out so quickly Jason.

**Comment by peebz** [comment]
It looks like a number of MELPA stable builds have occurred and the error is still there.

**Comment by jasonm23** [comment]
Thanks for the heads up

**Comment by jasonm23** [comment]
I may still need to retag master / HEAD as 0.2.x but for now I'm hoping I can get away with remaining on 0.1.6x.

I've deleted both of the 0.2.x tags and bumped the master branch to 0.1.66 (both in package version and git tag)

I will look into locking the MELPA releases so they only come from Master, but I think it's not possible.

My hope is that it uses a fresh clone of the repo, and what happens already is due to treating the tags as proper semantic versions.

I'll check back when the next MELPA Stable build has run.

**Comment by peebz** [comment]
That seems to have worked.  Many thanks.
