### ISSUE TITLE
provide a different background color for line numbers

### ISSUE THREAD

**Issue by mattsawyer77** [emacsfodder/emacs-theme-darktooth#61]
I really like darktooth the best of any emacs theme I've tried. I might be missing something here, as I'm very new to emacs, but it seems the line numbers have the same background as the main text, and with a wide gutter, it's hard to tell whether my code is indented properly.

**Comment by dieggsy** [comment]
They do have the same background color. I actually prefer this, but I keep my own fork so I'm mostly indifferent to the theme's default. One option would be to customize the face yourself (see `M-x customize-face RET` with `linum`, `linum-relative-current-face` and/or `nlinum-relative-current-face` as applicable).

Something to note is that starting with emacs 26, there is native support for line numbers in emacs (implemented in C rather than elisp) which are _way_ nicer and more performant than any elisp version out there IMO, and the fringe (which I think is what you meant by gutter?) is actually to the left of these rather than to the right.

Another side thought is that relying on visuals only to ensure proper indentation seems like more work than you should have to do, and `TAB` in many (most?) programming modes _should_ align correctly for you in emacs. In some cases (languages with properly delimited blocks like lisps, C, javascript, etc.) [aggressive-indent-mode](https://github.com/Malabarba/aggressive-indent-mode) is a godsend - keeps your code properly indented at all times. That said, I do understand that the indentation should _feel_ right in addition to _being_ right, heh.

**Comment by mattsawyer77** [comment]
Awesome, thanks for the info! I realized that part of my problem was that, in the midst of flailing around trying to learn how to configure various things, my line numbers became left-justified, and there was a big gap between the line numbers and the code. After restarting, the line numbers are right-aligned so it's not a big deal. I'll probably just go with the default for now.

Also, I agree with you that I shouldn't have the cognitive load of trying to indent correctly by eyeballing the screen -- I'll look into aggressive-indent-mode. Thanks!
